# Generated by Django 3.1.7 on 2021-03-31 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_is_microcontroller', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='meeting.jpg', upload_to='media/%Y/%m/%d')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('number_telephone', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='DataHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('temp_greenhouse_upstairs', models.CharField(max_length=7, verbose_name='Температура в теплице, в верхней части')),
                ('temp_greenhouse_downstairs', models.CharField(max_length=7, verbose_name='Температура в теплице, в нижней части')),
                ('temp_greenhouse_in_ground', models.CharField(max_length=7, verbose_name='Температура в теплице, в земле')),
                ('temp_street', models.CharField(max_length=7, verbose_name='Температура на улице')),
                ('humidity_greenhouse', models.CharField(max_length=10, verbose_name='Влажность в теплице')),
                ('humidity_greenhouse_in_ground', models.CharField(max_length=10, verbose_name='Влажность в теплице, в земли')),
                ('servo_turn_upstairs', models.CharField(max_length=4, verbose_name='Поворот нижнего сервопривода')),
                ('servo_turn_downstairs', models.CharField(max_length=4, verbose_name='Поворот верхнего сервопривода')),
                ('conditions_load_one', models.BooleanField(verbose_name='Первая нагрузка')),
                ('conditions_load_two', models.BooleanField(verbose_name='Вторая нагрузка')),
                ('conditions_load_three', models.BooleanField(verbose_name='Третья нагрузка')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_data', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликованно ли?')),
                ('on_check', models.BooleanField(default=False, verbose_name='Проверянно ли?')),
                ('owner_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to=settings.AUTH_USER_MODEL, verbose_name='Админ группы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Система подписок',
                'verbose_name_plural': 'Система подписок',
                'unique_together': {('user', 'owner_name')},
            },
        ),
    ]
