# Generated by Django 3.1.7 on 2021-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20210406_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_upstairs',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Температура в теплице, в верхней части'),
        ),
    ]
