# Generated by Django 3.1.7 on 2021-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20210406_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_upstairs',
            field=models.CharField(max_length=12, verbose_name='Температура в теплице, в верхней части'),
        ),
    ]
