# Generated by Django 3.1.7 on 2021-04-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20210406_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_downstairs',
            field=models.FloatField(verbose_name='Температура в теплице, в нижней части'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_in_ground',
            field=models.FloatField(verbose_name='Температура в теплице, в земле'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_upstairs',
            field=models.FloatField(verbose_name='Температура в теплице, в верхней части'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='temp_street',
            field=models.FloatField(verbose_name='Температура на улице'),
        ),
    ]
