# Generated by Django 3.1.7 on 2021-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20210406_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahouse',
            name='humidity_greenhouse',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Влажность в теплице'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='humidity_greenhouse_in_ground',
            field=models.IntegerField(verbose_name='Влажность в теплице, в земли'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='servo_turn_downstairs',
            field=models.IntegerField(verbose_name='Поворот верхнего сервопривода'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='servo_turn_upstairs',
            field=models.IntegerField(verbose_name='Поворот нижнего сервопривода'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_downstairs',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Температура в теплице, в нижней части'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_in_ground',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Температура в теплице, в земле'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='temp_greenhouse_upstairs',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Температура в теплице, в верхней части'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='temp_street',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Температура на улице'),
        ),
    ]
